spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/treestagram
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa: 
        show-sql: true
        hibernate: 
            ddl-auto: create
application: 
    jwt:
        expiresAt: 846000
        headerPrefix: "Bearer "
        secret: "s3cr3t"
        headerKey: "Authorization"
custom:
    prop: "salut"

# configuration du chemin de base pour swagger
springdoc:
    swagger-ui:
        path: /swagger